# Generated by Django 4.0.6 on 2022-09-14 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_brandmodel_colormodel_sizemodel_productmodel_brand_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='colormodel',
            options={'verbose_name': 'color', 'verbose_name_plural': 'colors'},
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='brand',
            new_name='brands',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='sale',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='productmodel',
            old_name='size',
            new_name='sizes',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='real_price',
            field=models.FloatField(default=0, verbose_name='real_price'),
        ),
    ]
