# Generated by Django 4.0.6 on 2022-09-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_colormodel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='sale'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='discount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='discount'),
        ),
    ]
